@baseurl = http://localhost:5000
# @baseurl = https://dieng-monitor-be.vercel.app

POST {{baseurl}}/devices/123/data
Content-Type: application/json

{
  "co2": 400,
  "temperature": 25
}

### export excel
GET {{baseurl}}/devices/123/excel

